/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/scene.glb 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { MeshStandardMaterial } from "three";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/scene.glb");
  const { actions } = useAnimations(animations, group);

  const mapMaterial = new MeshStandardMaterial({ color: 0x667b8b });
  const planeMaterial = new MeshStandardMaterial({ color: 0x031b2e
  });
  const wireMaterial = new MeshStandardMaterial({
    color: 0x20CBA2,
    wireframe: true,
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="fullworldObjectglb">
          <mesh
            name="Icosphere"
            geometry={nodes.Icosphere.geometry}
            material={planeMaterial}
            position={[0.004, 0, -0.004]}
          />
          <mesh
            name="map"
            geometry={nodes.map.geometry}
            material={mapMaterial}
            position={[0.97, -0.003, -0.109]}
            rotation={[2.121, 1.361, -2.131]}
            scale={3.193}
          />
          <mesh
            name="Sphere_wire"
            geometry={nodes.Sphere_wire.geometry}
            material={wireMaterial}
            position={[0.004, 0, -0.004]}
            rotation={[-Math.PI, 1.46, -Math.PI]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.glb");
